version: "3.5"

networks:
  network:

services:

  cdb1:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: wKMaHSzMDwWQ7U6Pwbxv9J6M
      COUCHDB_USER: admin
      NODENAME: couchdb1.demo.vme
      ERL_FLAGS: -setcookie KWSX4Nb4rF6WZDKPAAqDMy5K
    image: couchdb:2.2
    networks:
      network:
        aliases:
          - couchdb1.demo.vme
    ports:
      - "15984:5984"
      - "15986:5986"
    volumes:
      - ./vol/couchdb-configs/cluster.ini:/opt/couchdb/etc/local.d/cluster.ini:ro
    #   - "cdb1vol:/opt/couchdb/data"

  cdb2:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: wKMaHSzMDwWQ7U6Pwbxv9J6M
      COUCHDB_USER: admin
      NODENAME: couchdb2.demo.vme
      ERL_FLAGS: -setcookie KWSX4Nb4rF6WZDKPAAqDMy5K
    image: couchdb:2.2
    networks:
      network:
        aliases:
          - couchdb2.demo.vme
    ports:
      - "25984:5984"
      - "25986:5986"
    volumes:
      - ./vol/couchdb-configs/cluster.ini:/opt/couchdb/etc/local.d/cluster.ini:ro
    #   - "cdb2vol:/opt/couchdb/data"

  cdb3:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: wKMaHSzMDwWQ7U6Pwbxv9J6M
      COUCHDB_USER: admin
      NODENAME: couchdb3.demo.vme
      ERL_FLAGS: -setcookie KWSX4Nb4rF6WZDKPAAqDMy5K
    image: couchdb:2.2
    networks:
      network:
        aliases:
          - couchdb3.demo.vme
    ports:
      - "35984:5984"
      - "35986:5986"
    volumes:
      - ./vol/couchdb-configs/cluster.ini:/opt/couchdb/etc/local.d/cluster.ini:ro
    #   - "cdb3vol:/opt/couchdb/data"

  cdbadmin:
    image: alpine
    networks:
      network:
    volumes:
      - ./vol/scripts:/data
    entrypoint: /data/create_cluster.sh admin password couchdb1.demo.vme:5984 couchdb2.demo.vme:5984 couchdb3.demo.vme:5984
    depends_on:
      - cdb1
      - cdb2
      - cdb3

  haproxy:
    image: haproxy:1.8-alpine
    networks:
      network:
        aliases:
          - couchdb.demo.vme
    ports:
      - "5984:5984"
    volumes:
      - ./vol/haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - cdb1
      - cdb2
      - cdb3

  nginx:
    image: nginx:alpine
    networks:
      network:
        aliases:
          - couchdb-nginx.demo.vme
    ports:
      - "55984:5984"
    volumes:
      - ./vol/nginx/couchdb_lb.conf:/etc/nginx/conf.d/couchdb_lb.conf:ro
    depends_on:
      - cdb1
      - cdb2
      - cdb3
      
# volumes:
#   cdb1vol:
#   cdb2vol:
#   cdb3vol:
